# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

# 每天10:30执行

name: BiTask

on:
   push:
     paths: 
        - '**/Bilibili.yml'
   gollum:
   workflow_dispatch:
   schedule:
       - cron: '30 9 * * *'
   watch:
    types: started

jobs:
  start:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle
    - name: Clone lastest source code
      run: |
         git clone https://github.com/srcrs/BilibiliTask.git ./taskcode
    - name: Build with Gradle
      working-directory: ./taskcode
      env:
        BILI_JCT: ${{ secrets.BILI_JCT }}
        DEDEUSERID: ${{ secrets.DEDEUSERID }}
        SESSDATA: ${{ secrets.SESSDATA }}
        SCKEY: ${{ secrets.SCKEY }}
        DINGTALK: ${{secrets.DINGTALK}}
        PUSHPLUSTK: ${{secrets.PUSHPLUSTK}}
      run:
        sh gradlew runMain
